
[tool.isort]
profile = "black"
line_length = 100

[tool.black]
line-length = 100

[tool.ruff]
line-length = 100

[tool.mypy]
ignore_missing_imports = true
strict = true
plugins = "pydantic.mypy"

# [tool.bandit]
# exclude_dirs = ['tests', 'path/to/file']
# tests = ["B201", "B301"]
# skips = ["B101", "B601"]

# [mypy]
# plugins = pydantic.mypy


[[tool.mypy.overrides]]
module = ["helloworld.v1.*"]
ignore_errors = true

[[tool.mypy.overrides]]
module = ["calc.v1.*"]
ignore_errors = true

[[tool.mypy.overrides]]
module = ["tests.*"]
# ignore_errors = true
# comparison_overlap = false
disable_error_code =[
    "comparison-overlap",
]

# [tool.pytest.ini_options]
[tool.pytest]
addopts ="--cov-report=html"

