run:
	AWS_DEFAULT_REGION=ap-northeast-1 \
    AWS_ACCESS_KEY_ID=access_key_id \
    AWS_SECRET_ACCESS_KEY=secret_access_key \
    AWS_ENDPOINT_URL=http://127.0.0.1:4566 \
	pants run :kinesis_producer
