# python_sources(
#     resolve="asyncio_cpu_test",
#     interpreter_constraints=["CPython>=3.11"],
#     # sources=["*.py"],
# )

# #python_sources(
# #    name="src",
# #    resolve="asyncio_cpu_test",
# #    interpreter_constraints=["CPython>=3.11"],
# #    sources=["asyncio_cpu_test/**/*.py"],
# #    dependencies=[
# #    ],
# #)
