[tool.poetry]
name = "lib-pydantic-v1"
version = "0.1.0"
description = ""
authors = ["pecolynx <pecolynx@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pydantic = "1.10.17"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
